name: Hello World! # This is name of the workflow
on: # This is used to manage the workflow triggering
 push:
 branches:
 - master
jobs: # This is the code that will be executed when workflow triggers
 hello_world_job: # Name of the Job
runs-on: [ubuntu-20.04] # The GitHub runner will use Ubuntu 20.04 as OS
 steps:
 - name: Say hello
 run: echo "Hello World!"
